version: "2.0"
services:
    logspout:
       image: "gliderlabs/logspout"
       container_name: "logspout"
       hostname: "logspout"
       privileged: true
       restart: "always"
       stdin_open: true
       tty: true
       command: "syslog+tcp://puppet.kar.int:5003"
       volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
       network_mode: "bridge"
       labels:
        - com.centurylinklabs.watchtower.enable=true
