version: '2'
services:

    mariadb:
       image: mariadb:latest
       container_name: mariadb2
       hostname: mariadb2
       restart: always
       ports:
        - "3307:3306"
       network_mode: bridge
#       environment:
#         - MYSQL_ROOT_PASSWORD="testing"

