version: '2'
services:

  watchtower:
    image: v2tec/watchtower:latest
    hostname: watchtower
    container_name: watchtower
    command: -i 86400 --cleanup --label-enable
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    network_mode: "bridge"
    environment:
      - "WATCHTOWER_NOTIFICATIONS=email"
      - "WATCHTOWER_NOTIFICATION_EMAIL_FROM=watchtower@ub.kar.int"
      - "WATCHTOWER_NOTIFICATION_EMAIL_TO=elatov@kerch.kar.int"
      - "WATCHTOWER_NOTIFICATION_EMAIL_SERVER=10.0.0.2"
    labels:
      - com.centurylinklabs.watchtower.enable=true
